string object_type # type of the object one wants the costmap for
float64[] placed_x_object_positions # the x position of the base objects
float64[] placed_y_object_positions # the y position of the base objects
string[] placed_object_types # types of the placed objects
string context # describing the task proceeded during the vr data collection
string name # name of the human who recorded the vr data
string kitchen # name of the kitchen
string table_id # name of the table
string location # name of the location used in the OWL
---
float64[] means
float64[] covs
float64[] weights
geometry_msgs/Point[] bottem_lefts # bottom left point of x_y_points in the map frame of kitchen
float64[] widths # width of x_y_points in [m]
float64[] heights # height of x_y_points in [m]
float64[] angles # contains pairs of means and covs repeatably